### ISSUE TITLE
引入ts-loader库后导致跳转文件会失效

### ISSUE THREAD

**Issue by semgilo** [zombieyang/puerts-ts-loader#1]
环境：
* 硬件：macbook-pro m1 2021
* 系统：macos 13.0.1 (22A400)
* 测试demo:
https://github.com/semgilo/demo-puerts

**Comment by zombieyang** [comment]
你这个demo一行代码都没有..
我用Sample1能复现出cs文件跳转失效的问题，ts文件看上去正常
