### ISSUE TITLE
Sample 2 在安卓设备中运行报错

### ISSUE THREAD

**Issue by 1162064779** [zombieyang/puerts-ts-loader#8]
![puer](https://github.com/zombieyang/puerts-ts-loader/assets/43094910/ffb8b8ae-4cba-41ea-9de8-ebc286f4cf87)
我在我的unity项目中照着readme安装了tsloader并引入了sample2的测试代码，在editor下可以正常运行，但在打包成apk运行在安卓设备上时出现了问题，同时puerts的测试样例是好使的。
以下是我大致的项目结构：
![image](https://github.com/zombieyang/puerts-ts-loader/assets/43094910/26be7435-7091-40d8-80f2-30e443f73498)
![image](https://github.com/zombieyang/puerts-ts-loader/assets/43094910/b6404c8a-d2d8-4a1e-b758-a28c8498b529)

**Comment by zombieyang** [comment]
点了release JS了吗？

**Comment by 1162064779** [comment]
> 点了release JS了吗？

感谢您的回复，不知道您说的是下面这个嘛，我之前确实没有点，现在它为我生成了如下文件，这让我高兴，但遗憾的是，在android设备上的运行结果同样是报错：Exception: __puer_execute__.mjs:183: Error: [Puer002]import main.mts failed: module not found，我会再在此基础上做一些其他尝试，再次感谢您的回复！
![image](https://github.com/zombieyang/puerts-ts-loader/assets/43094910/147a13cc-9953-41c6-8d51-e383d11a3ec6)

**Comment by zombieyang** [comment]
Sample2依赖于Node.js Backend，确认下你安卓的so是不是采用了NodeJS版Puerts

**Comment by 1162064779** [comment]
> Sample2依赖于Node.js Backend，确认下你安卓的so是不是采用了NodeJS版Puerts

感谢您的再次回复，我不确定哪里可以看到我puerts的backend，所以我尝试了如下方法来判断当前的运行环境：
![image](https://github.com/zombieyang/puerts-ts-loader/assets/43094910/6084d1bc-df23-46c9-a74e-bedf2f02ec81)
然后这是我的日志，确实应该是nodejs的，我发现将sample2中的mts用tsc转成mjs后，在安卓上可以运行了，虽然也有警告，我不确定是不是sample2不可以在安卓上运行的缘故，您的tsloader是专供于editor运行ts使用的是吗？我的感觉就像是项目经过安卓打包后puerts可以找到mjs文件但找不到mts文件：
![image](https://github.com/zombieyang/puerts-ts-loader/assets/43094910/4a84ef32-021e-4dc2-a00b-e7cba7dddc9a)
